# Generated by Django 4.0.10 on 2023-05-12 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_alter_account_options_alter_code_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionidforaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
