# Generated by Django 4.0.10 on 2023-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_verify',
            field=models.BooleanField(default=False),
        ),
    ]
