# Generated by Django 4.0.10 on 2023-05-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_account_phone_verify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionIdForAccount',
        ),
    ]
