# Generated by Django 4.0.10 on 2023-05-13 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0007_delete_sessionidforaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_person_name', models.CharField(max_length=250, verbose_name="Jo'natuvchi Shahsning ismi")),
                ('product_name', models.CharField(max_length=500, verbose_name='Mahsulot nomi')),
                ('product_weight', models.CharField(max_length=250, verbose_name="Mahsulotning o'girligi")),
                ('product_price', models.CharField(max_length=500, verbose_name='Mahsulotning narxi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('client_name', models.CharField(max_length=500, verbose_name='Oluvchi shahsning ismi')),
                ('client_phone_number', models.CharField(max_length=50, verbose_name='Oluvchi shahsning tel raqami')),
                ('product_status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('way', "Yo'lda"), ('archived', 'Arxivlandi')], max_length=50, verbose_name='Mahsulotning Holati')),
                ('sender_person_phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Jo'natuvchi Shahsning tel raqami")),
            ],
            options={
                'verbose_name': 'Buyurtmalar',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
    ]
