# Generated by Django 4.0.10 on 2023-05-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Telefon raqam'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_verify',
            field=models.BooleanField(default=False, verbose_name='Telefon raqam tekshirish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_status',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ("Yo'lda", "Yo'lda"), ('Arxivlandi', 'Arxivlandi')], max_length=50, verbose_name='Mahsulotning Holati'),
        ),
    ]
