# Generated by Django 4.0.10 on 2023-05-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0009_alter_account_first_name_alter_account_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Done_Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='Jobs')),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'Bajarilgan ishlar',
                'verbose_name_plural': 'Bajarilgan ishlar',
            },
        ),
    ]
